site_name: 无刃传说
theme: readthedocs
nav:
  - 主页: index.md
  - 团队: team.md
  - 世界观规划: worldview_planning.md
  - 剧情: plot.md
  - 剧本和演出: script_and_performances.md
  - 玩法及数值设计: gameplay_and_numerical_design.md
  - 艺术设计: art_design.md
  - 音频设计: audio_design.md
  - 本地化: localization.md